import { NextResponse } from "next/server"

// Expanded mock database of songs with more entries and better variety
const songDatabase = [
  // Happy songs
  {
    id: 101,
    title: "Happy",
    artist: "Pharrell Williams",
    duration: "3:53",
    durationSeconds: 233,
    bpm: 160,
    energy: 75,
    genres: ["Pop", "R&B"],
    mood: "happy",
  },
  {
    id: 102,
    title: "Can't Stop the Feeling!",
    artist: "Justin Timberlake",
    duration: "3:56",
    durationSeconds: 236,
    bpm: 113,
    energy: 80,
    genres: ["Pop", "Disco"],
    mood: "happy",
  },
  {
    id: 103,
    title: "Good as Hell",
    artist: "Lizzo",
    duration: "2:39",
    durationSeconds: 159,
    bpm: 96,
    energy: 65,
    genres: ["Pop", "R&B"],
    mood: "happy",
  },
  {
    id: 104,
    title: "Walking on Sunshine",
    artist: "Katrina & The Waves",
    duration: "3:58",
    durationSeconds: 238,
    bpm: 110,
    energy: 85,
    genres: ["Pop", "Rock"],
    mood: "happy",
  },
  {
    id: 105,
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    duration: "4:30",
    durationSeconds: 270,
    bpm: 115,
    energy: 82,
    genres: ["Pop", "Funk", "R&B"],
    mood: "happy",
  },
  {
    id: 106,
    title: "I Gotta Feeling",
    artist: "Black Eyed Peas",
    duration: "4:49",
    durationSeconds: 289,
    bpm: 128,
    energy: 75,
    genres: ["Pop", "Electronic"],
    mood: "happy",
  },
  {
    id: 107,
    title: "Shake It Off",
    artist: "Taylor Swift",
    duration: "3:39",
    durationSeconds: 219,
    bpm: 160,
    energy: 80,
    genres: ["Pop"],
    mood: "happy",
  },
  {
    id: 108,
    title: "Don't Stop Me Now",
    artist: "Queen",
    duration: "3:29",
    durationSeconds: 209,
    bpm: 156,
    energy: 90,
    genres: ["Rock"],
    mood: "happy",
  },
  {
    id: 109,
    title: "Dancing Queen",
    artist: "ABBA",
    duration: "3:51",
    durationSeconds: 231,
    bpm: 100,
    energy: 75,
    genres: ["Pop", "Disco"],
    mood: "happy",
  },
  {
    id: 110,
    title: "September",
    artist: "Earth, Wind & Fire",
    duration: "3:35",
    durationSeconds: 215,
    bpm: 126,
    energy: 80,
    genres: ["Funk", "R&B"],
    mood: "happy",
  },
  {
    id: 111,
    title: "Dynamite",
    artist: "BTS",
    duration: "3:19",
    durationSeconds: 199,
    bpm: 114,
    energy: 75,
    genres: ["Pop", "K-Pop"],
    mood: "happy",
  },
  {
    id: 112,
    title: "Good Vibrations",
    artist: "The Beach Boys",
    duration: "3:39",
    durationSeconds: 219,
    bpm: 117,
    energy: 70,
    genres: ["Pop", "Rock"],
    mood: "happy",
  },
  {
    id: 113,
    title: "Celebration",
    artist: "Kool & The Gang",
    duration: "4:58",
    durationSeconds: 298,
    bpm: 121,
    energy: 75,
    genres: ["Funk", "R&B"],
    mood: "happy",
  },
  {
    id: 114,
    title: "Best Day of My Life",
    artist: "American Authors",
    duration: "3:14",
    durationSeconds: 194,
    bpm: 100,
    energy: 80,
    genres: ["Pop", "Rock"],
    mood: "happy",
  },
  {
    id: 115,
    title: "Shut Up and Dance",
    artist: "Walk The Moon",
    duration: "3:17",
    durationSeconds: 197,
    bpm: 128,
    energy: 85,
    genres: ["Pop", "Rock"],
    mood: "happy",
  },
  {
    id: 116,
    title: "24K Magic",
    artist: "Bruno Mars",
    duration: "3:46",
    durationSeconds: 226,
    bpm: 107,
    energy: 80,
    genres: ["Pop", "Funk", "R&B"],
    mood: "happy",
  },
  {
    id: 117,
    title: "Juice",
    artist: "Lizzo",
    duration: "3:15",
    durationSeconds: 195,
    bpm: 82,
    energy: 70,
    genres: ["Pop", "R&B"],
    mood: "happy",
  },
  {
    id: 118,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    duration: "2:54",
    durationSeconds: 174,
    bpm: 95,
    energy: 65,
    genres: ["Pop", "Rock"],
    mood: "happy",
  },
  {
    id: 119,
    title: "Blinding Lights",
    artist: "The Weeknd",
    duration: "3:20",
    durationSeconds: 200,
    bpm: 171,
    energy: 80,
    genres: ["Pop", "Synth-pop"],
    mood: "happy",
  },
  {
    id: 120,
    title: "Levitating",
    artist: "Dua Lipa",
    duration: "3:23",
    durationSeconds: 203,
    bpm: 103,
    energy: 75,
    genres: ["Pop", "Disco"],
    mood: "happy",
  },

  // Chill songs
  {
    id: 201,
    title: "Waves",
    artist: "Chill Beats",
    duration: "4:12",
    durationSeconds: 252,
    bpm: 70,
    energy: 30,
    genres: ["Lo-fi", "Electronic"],
    mood: "chill",
  },
  {
    id: 202,
    title: "Sunday Morning",
    artist: "Maroon 5",
    duration: "4:06",
    durationSeconds: 246,
    bpm: 90,
    energy: 40,
    genres: ["Pop", "R&B"],
    mood: "chill",
  },
  {
    id: 203,
    title: "Breathe",
    artist: "Télépopmusik",
    duration: "4:40",
    durationSeconds: 280,
    bpm: 80,
    energy: 35,
    genres: ["Electronic", "Downtempo"],
    mood: "chill",
  },
  {
    id: 204,
    title: "Midnight City",
    artist: "M83",
    duration: "4:01",
    durationSeconds: 241,
    bpm: 105,
    energy: 60,
    genres: ["Electronic", "Indie"],
    mood: "chill",
  },
  {
    id: 205,
    title: "Sunset Lover",
    artist: "Petit Biscuit",
    duration: "3:56",
    durationSeconds: 236,
    bpm: 102,
    energy: 45,
    genres: ["Electronic", "Chill"],
    mood: "chill",
  },
  {
    id: 206,
    title: "Coffee",
    artist: "Beabadoobee",
    duration: "3:26",
    durationSeconds: 206,
    bpm: 85,
    energy: 40,
    genres: ["Indie", "Lo-fi"],
    mood: "chill",
  },
  {
    id: 207,
    title: "Flume",
    artist: "Bon Iver",
    duration: "3:39",
    durationSeconds: 219,
    bpm: 80,
    energy: 35,
    genres: ["Indie", "Folk"],
    mood: "chill",
  },
  {
    id: 208,
    title: "Holocene",
    artist: "Bon Iver",
    duration: "5:36",
    durationSeconds: 336,
    bpm: 73,
    energy: 40,
    genres: ["Indie", "Folk"],
    mood: "chill",
  },
  {
    id: 209,
    title: "Myth",
    artist: "Beach House",
    duration: "4:18",
    durationSeconds: 258,
    bpm: 105,
    energy: 50,
    genres: ["Indie", "Dream Pop"],
    mood: "chill",
  },
  {
    id: 210,
    title: "Redbone",
    artist: "Childish Gambino",
    duration: "5:27",
    durationSeconds: 327,
    bpm: 75,
    energy: 55,
    genres: ["R&B", "Funk"],
    mood: "chill",
  },
  {
    id: 211,
    title: "Taro",
    artist: "Alt-J",
    duration: "5:05",
    durationSeconds: 305,
    bpm: 63,
    energy: 45,
    genres: ["Indie", "Alternative"],
    mood: "chill",
  },
  {
    id: 212,
    title: "Innerbloom",
    artist: "RÜFÜS DU SOL",
    duration: "9:38",
    durationSeconds: 578,
    bpm: 122,
    energy: 60,
    genres: ["Electronic", "Deep House"],
    mood: "chill",
  },
  {
    id: 213,
    title: "Bloom",
    artist: "Odesza",
    duration: "4:10",
    durationSeconds: 250,
    bpm: 120,
    energy: 65,
    genres: ["Electronic", "Chillwave"],
    mood: "chill",
  },
  {
    id: 214,
    title: "Slow Dancing In A Burning Room",
    artist: "John Mayer",
    duration: "4:02",
    durationSeconds: 242,
    bpm: 80,
    energy: 45,
    genres: ["Blues", "Pop"],
    mood: "chill",
  },
  {
    id: 215,
    title: "Retrograde",
    artist: "James Blake",
    duration: "3:43",
    durationSeconds: 223,
    bpm: 90,
    energy: 50,
    genres: ["Electronic", "Soul"],
    mood: "chill",
  },
  {
    id: 216,
    title: "Nightcall",
    artist: "Kavinsky",
    duration: "4:19",
    durationSeconds: 259,
    bpm: 90,
    energy: 55,
    genres: ["Electronic", "Synthwave"],
    mood: "chill",
  },
  {
    id: 217,
    title: "Intro",
    artist: "The xx",
    duration: "2:07",
    durationSeconds: 127,
    bpm: 90,
    energy: 35,
    genres: ["Indie", "Electronic"],
    mood: "chill",
  },
  {
    id: 218,
    title: "Teardrop",
    artist: "Massive Attack",
    duration: "5:30",
    durationSeconds: 330,
    bpm: 79,
    energy: 45,
    genres: ["Trip Hop", "Electronic"],
    mood: "chill",
  },
  {
    id: 219,
    title: "Fade Into You",
    artist: "Mazzy Star",
    duration: "4:55",
    durationSeconds: 295,
    bpm: 80,
    energy: 30,
    genres: ["Alternative", "Dream Pop"],
    mood: "chill",
  },
  {
    id: 220,
    title: "Porcelain",
    artist: "Moby",
    duration: "4:01",
    durationSeconds: 241,
    bpm: 96,
    energy: 40,
    genres: ["Electronic", "Ambient"],
    mood: "chill",
  },

  // Energetic songs
  {
    id: 301,
    title: "Higher Ground",
    artist: "ODESZA",
    duration: "3:42",
    durationSeconds: 222,
    bpm: 120,
    energy: 85,
    genres: ["Electronic", "Dance"],
    mood: "energetic",
  },
  {
    id: 302,
    title: "Don't Stop Me Now",
    artist: "Queen",
    duration: "3:29",
    durationSeconds: 209,
    bpm: 156,
    energy: 90,
    genres: ["Rock"],
    mood: "energetic",
  },
  {
    id: 303,
    title: "Levels",
    artist: "Avicii",
    duration: "3:19",
    durationSeconds: 199,
    bpm: 126,
    energy: 88,
    genres: ["Electronic", "Dance"],
    mood: "energetic",
  },
  {
    id: 304,
    title: "Can't Hold Us",
    artist: "Macklemore & Ryan Lewis",
    duration: "4:18",
    durationSeconds: 258,
    bpm: 146,
    energy: 93,
    genres: ["Hip Hop", "Pop"],
    mood: "energetic",
  },
  {
    id: 305,
    title: "Wake Me Up",
    artist: "Avicii",
    duration: "4:07",
    durationSeconds: 247,
    bpm: 124,
    energy: 80,
    genres: ["Electronic", "Folk"],
    mood: "energetic",
  },
  {
    id: 306,
    title: "Titanium",
    artist: "David Guetta ft. Sia",
    duration: "4:05",
    durationSeconds: 245,
    bpm: 126,
    energy: 82,
    genres: ["Electronic", "Pop"],
    mood: "energetic",
  },
  {
    id: 307,
    title: "Sandstorm",
    artist: "Darude",
    duration: "3:53",
    durationSeconds: 233,
    bpm: 136,
    energy: 95,
    genres: ["Electronic", "Trance"],
    mood: "energetic",
  },
  {
    id: 308,
    title: "Harder, Better, Faster, Stronger",
    artist: "Daft Punk",
    duration: "3:45",
    durationSeconds: 225,
    bpm: 123,
    energy: 90,
    genres: ["Electronic", "House"],
    mood: "energetic",
  },
  {
    id: 309,
    title: "Thunderclouds",
    artist: "LSD",
    duration: "3:59",
    durationSeconds: 239,
    bpm: 110,
    energy: 85,
    genres: ["Pop", "Electronic"],
    mood: "energetic",
  },
  {
    id: 310,
    title: "Believer",
    artist: "Imagine Dragons",
    duration: "3:24",
    durationSeconds: 204,
    bpm: 125,
    energy: 88,
    genres: ["Pop", "Rock"],
    mood: "energetic",
  },
  {
    id: 311,
    title: "Centuries",
    artist: "Fall Out Boy",
    duration: "3:33",
    durationSeconds: 213,
    bpm: 140,
    energy: 90,
    genres: ["Rock", "Pop"],
    mood: "energetic",
  },
  {
    id: 312,
    title: "Lose Yourself",
    artist: "Eminem",
    duration: "5:26",
    durationSeconds: 326,
    bpm: 171,
    energy: 93,
    genres: ["Hip Hop", "Rap"],
    mood: "energetic",
  },
  {
    id: 313,
    title: "Eye of the Tiger",
    artist: "Survivor",
    duration: "4:05",
    durationSeconds: 245,
    bpm: 109,
    energy: 85,
    genres: ["Rock"],
    mood: "energetic",
  },
  {
    id: 314,
    title: "Till I Collapse",
    artist: "Eminem",
    duration: "4:57",
    durationSeconds: 297,
    bpm: 171,
    energy: 90,
    genres: ["Hip Hop", "Rap"],
    mood: "energetic",
  },
  {
    id: 315,
    title: "Stronger",
    artist: "Kanye West",
    duration: "5:12",
    durationSeconds: 312,
    bpm: 104,
    energy: 85,
    genres: ["Hip Hop", "Rap"],
    mood: "energetic",
  },
  {
    id: 316,
    title: "Power",
    artist: "Kanye West",
    duration: "4:52",
    durationSeconds: 292,
    bpm: 154,
    energy: 88,
    genres: ["Hip Hop", "Rap"],
    mood: "energetic",
  },
  {
    id: 317,
    title: "Pump It",
    artist: "Black Eyed Peas",
    duration: "3:35",
    durationSeconds: 215,
    bpm: 154,
    energy: 90,
    genres: ["Pop", "Hip Hop"],
    mood: "energetic",
  },
  {
    id: 318,
    title: "Blinding Lights",
    artist: "The Weeknd",
    duration: "3:20",
    durationSeconds: 200,
    bpm: 171,
    energy: 80,
    genres: ["Pop", "Synth-pop"],
    mood: "energetic",
  },
  {
    id: 319,
    title: "Uprising",
    artist: "Muse",
    duration: "5:03",
    durationSeconds: 303,
    bpm: 116,
    energy: 85,
    genres: ["Rock", "Alternative"],
    mood: "energetic",
  },
  {
    id: 320,
    title: "Seven Nation Army",
    artist: "The White Stripes",
    duration: "3:51",
    durationSeconds: 231,
    bpm: 124,
    energy: 80,
    genres: ["Rock", "Alternative"],
    mood: "energetic",
  },

  // Melancholic songs
  {
    id: 401,
    title: "Someone Like You",
    artist: "Adele",
    duration: "4:45",
    durationSeconds: 285,
    bpm: 68,
    energy: 30,
    genres: ["Pop", "Soul"],
    mood: "melancholic",
  },
  {
    id: 402,
    title: "Fix You",
    artist: "Coldplay",
    duration: "4:55",
    durationSeconds: 295,
    bpm: 74,
    energy: 40,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 403,
    title: "Skinny Love",
    artist: "Bon Iver",
    duration: "3:58",
    durationSeconds: 238,
    bpm: 80,
    energy: 35,
    genres: ["Indie", "Folk"],
    mood: "melancholic",
  },
  {
    id: 404,
    title: "Hurt",
    artist: "Johnny Cash",
    duration: "3:38",
    durationSeconds: 218,
    bpm: 75,
    energy: 30,
    genres: ["Country", "Folk"],
    mood: "melancholic",
  },
  {
    id: 405,
    title: "Creep",
    artist: "Radiohead",
    duration: "3:56",
    durationSeconds: 236,
    bpm: 92,
    energy: 45,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 406,
    title: "Hallelujah",
    artist: "Jeff Buckley",
    duration: "6:53",
    durationSeconds: 413,
    bpm: 65,
    energy: 25,
    genres: ["Folk", "Rock"],
    mood: "melancholic",
  },
  {
    id: 407,
    title: "Mad World",
    artist: "Gary Jules",
    duration: "3:09",
    durationSeconds: 189,
    bpm: 87,
    energy: 30,
    genres: ["Pop", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 408,
    title: "The Night We Met",
    artist: "Lord Huron",
    duration: "3:28",
    durationSeconds: 208,
    bpm: 120,
    energy: 35,
    genres: ["Indie", "Folk"],
    mood: "melancholic",
  },
  {
    id: 409,
    title: "Everybody Hurts",
    artist: "R.E.M.",
    duration: "5:17",
    durationSeconds: 317,
    bpm: 110,
    energy: 40,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 410,
    title: "Nothing Compares 2 U",
    artist: "Sinéad O'Connor",
    duration: "5:07",
    durationSeconds: 307,
    bpm: 120,
    energy: 35,
    genres: ["Pop", "Rock"],
    mood: "melancholic",
  },
  {
    id: 411,
    title: "Tears in Heaven",
    artist: "Eric Clapton",
    duration: "4:36",
    durationSeconds: 276,
    bpm: 80,
    energy: 30,
    genres: ["Rock", "Folk"],
    mood: "melancholic",
  },
  {
    id: 412,
    title: "Breathe Me",
    artist: "Sia",
    duration: "4:34",
    durationSeconds: 274,
    bpm: 92,
    energy: 40,
    genres: ["Pop", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 413,
    title: "Landslide",
    artist: "Fleetwood Mac",
    duration: "3:19",
    durationSeconds: 199,
    bpm: 78,
    energy: 25,
    genres: ["Rock", "Folk"],
    mood: "melancholic",
  },
  {
    id: 414,
    title: "Chasing Cars",
    artist: "Snow Patrol",
    duration: "4:27",
    durationSeconds: 267,
    bpm: 104,
    energy: 45,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 415,
    title: "Hurt",
    artist: "Nine Inch Nails",
    duration: "6:13",
    durationSeconds: 373,
    bpm: 75,
    energy: 40,
    genres: ["Industrial", "Rock"],
    mood: "melancholic",
  },
  {
    id: 416,
    title: "Liability",
    artist: "Lorde",
    duration: "2:52",
    durationSeconds: 172,
    bpm: 72,
    energy: 25,
    genres: ["Pop", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 417,
    title: "Runaway",
    artist: "Kanye West",
    duration: "9:08",
    durationSeconds: 548,
    bpm: 87,
    energy: 40,
    genres: ["Hip Hop", "Rap"],
    mood: "melancholic",
  },
  {
    id: 418,
    title: "Wish You Were Here",
    artist: "Pink Floyd",
    duration: "5:35",
    durationSeconds: 335,
    bpm: 66,
    energy: 35,
    genres: ["Rock", "Progressive"],
    mood: "melancholic",
  },
  {
    id: 419,
    title: "Disarm",
    artist: "Smashing Pumpkins",
    duration: "3:17",
    durationSeconds: 197,
    bpm: 80,
    energy: 40,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },
  {
    id: 420,
    title: "Asleep",
    artist: "The Smiths",
    duration: "4:09",
    durationSeconds: 249,
    bpm: 70,
    energy: 25,
    genres: ["Rock", "Alternative"],
    mood: "melancholic",
  },

  // Focus songs
  {
    id: 501,
    title: "Experience",
    artist: "Ludovico Einaudi",
    duration: "5:15",
    durationSeconds: 315,
    bpm: 90,
    energy: 40,
    genres: ["Classical", "Instrumental"],
    mood: "focus",
  },
  {
    id: 502,
    title: "Strobe",
    artist: "deadmau5",
    duration: "10:37",
    durationSeconds: 637,
    bpm: 128,
    energy: 60,
    genres: ["Electronic", "Progressive House"],
    mood: "focus",
  },
  {
    id: 503,
    title: "Intro",
    artist: "The xx",
    duration: "2:07",
    durationSeconds: 127,
    bpm: 90,
    energy: 35,
    genres: ["Indie", "Electronic"],
    mood: "focus",
  },
  {
    id: 504,
    title: "Avril 14th",
    artist: "Aphex Twin",
    duration: "2:05",
    durationSeconds: 125,
    bpm: 84,
    energy: 30,
    genres: ["Electronic", "Ambient"],
    mood: "focus",
  },
  {
    id: 505,
    title: "Gymnopédie No.1",
    artist: "Erik Satie",
    duration: "3:05",
    durationSeconds: 185,
    bpm: 60,
    energy: 20,
    genres: ["Classical", "Piano"],
    mood: "focus",
  },
  {
    id: 506,
    title: "Divenire",
    artist: "Ludovico Einaudi",
    duration: "6:42",
    durationSeconds: 402,
    bpm: 90,
    energy: 45,
    genres: ["Classical", "Instrumental"],
    mood: "focus",
  },
  {
    id: 507,
    title: "Nuvole Bianche",
    artist: "Ludovico Einaudi",
    duration: "5:57",
    durationSeconds: 357,
    bpm: 80,
    energy: 35,
    genres: ["Classical", "Piano"],
    mood: "focus",
  },
  {
    id: 508,
    title: "Time",
    artist: "Hans Zimmer",
    duration: "4:35",
    durationSeconds: 275,
    bpm: 60,
    energy: 50,
    genres: ["Soundtrack", "Instrumental"],
    mood: "focus",
  },
  {
    id: 509,
    title: "Comptine d'un autre été",
    artist: "Yann Tiersen",
    duration: "2:21",
    durationSeconds: 141,
    bpm: 80,
    energy: 30,
    genres: ["Soundtrack", "Piano"],
    mood: "focus",
  },
  {
    id: 510,
    title: "Clair de Lune",
    artist: "Claude Debussy",
    duration: "5:01",
    durationSeconds: 301,
    bpm: 70,
    energy: 25,
    genres: ["Classical", "Piano"],
    mood: "focus",
  },
  {
    id: 511,
    title: "Weightless",
    artist: "Marconi Union",
    duration: "8:09",
    durationSeconds: 489,
    bpm: 60,
    energy: 20,
    genres: ["Ambient", "Electronic"],
    mood: "focus",
  },
  {
    id: 512,
    title: "An Ending (Ascent)",
    artist: "Brian Eno",
    duration: "4:26",
    durationSeconds: 266,
    bpm: 75,
    energy: 25,
    genres: ["Ambient", "Electronic"],
    mood: "focus",
  },
  {
    id: 513,
    title: "Metamorphosis One",
    artist: "Philip Glass",
    duration: "5:38",
    durationSeconds: 338,
    bpm: 96,
    energy: 40,
    genres: ["Classical", "Minimalist"],
    mood: "focus",
  },
  {
    id: 514,
    title: "Adagio for Strings",
    artist: "Samuel Barber",
    duration: "7:25",
    durationSeconds: 445,
    bpm: 55,
    energy: 35,
    genres: ["Classical", "Orchestral"],
    mood: "focus",
  },
  {
    id: 515,
    title: "Arrival of the Birds",
    artist: "The Cinematic Orchestra",
    duration: "2:34",
    durationSeconds: 154,
    bpm: 80,
    energy: 40,
    genres: ["Soundtrack", "Orchestral"],
    mood: "focus",
  },
  {
    id: 516,
    title: "Opus 23",
    artist: "Dustin O'Halloran",
    duration: "4:14",
    durationSeconds: 254,
    bpm: 70,
    energy: 30,
    genres: ["Classical", "Piano"],
    mood: "focus",
  },
  {
    id: 517,
    title: "Horizon Variations",
    artist: "Max Richter",
    duration: "1:41",
    durationSeconds: 101,
    bpm: 65,
    energy: 25,
    genres: ["Classical", "Ambient"],
    mood: "focus",
  },
  {
    id: 518,
    title: "Spiegel im Spiegel",
    artist: "Arvo Pärt",
    duration: "8:58",
    durationSeconds: 538,
    bpm: 60,
    energy: 20,
    genres: ["Classical", "Minimalist"],
    mood: "focus",
  },
  {
    id: 519,
    title: "Ambient 1/Music for Airports",
    artist: "Brian Eno",
    duration: "17:37",
    durationSeconds: 1057,
    bpm: 60,
    energy: 15,
    genres: ["Ambient", "Electronic"],
    mood: "focus",
  },
  {
    id: 520,
    title: "Metamorphosis Two",
    artist: "Philip Glass",
    duration: "7:21",
    durationSeconds: 441,
    bpm: 96,
    energy: 40,
    genres: ["Classical", "Minimalist"],
    mood: "focus",
  },

  // Romantic songs
  {
    id: 601,
    title: "All of Me",
    artist: "John Legend",
    duration: "4:29",
    durationSeconds: 269,
    bpm: 120,
    energy: 40,
    genres: ["R&B", "Soul"],
    mood: "romantic",
  },
  {
    id: 602,
    title: "Perfect",
    artist: "Ed Sheeran",
    duration: "4:23",
    durationSeconds: 263,
    bpm: 95,
    energy: 45,
    genres: ["Pop", "Folk"],
    mood: "romantic",
  },
  {
    id: 603,
    title: "At Last",
    artist: "Etta James",
    duration: "2:59",
    durationSeconds: 179,
    bpm: 87,
    energy: 35,
    genres: ["Jazz", "Soul"],
    mood: "romantic",
  },
  {
    id: 604,
    title: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    duration: "3:02",
    durationSeconds: 182,
    bpm: 80,
    energy: 30,
    genres: ["Pop", "Rock"],
    mood: "romantic",
  },
  {
    id: 605,
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
    duration: "4:41",
    durationSeconds: 281,
    bpm: 79,
    energy: 45,
    genres: ["Pop", "Soul"],
    mood: "romantic",
  },
  {
    id: 606,
    title: "Make You Feel My Love",
    artist: "Adele",
    duration: "3:32",
    durationSeconds: 212,
    bpm: 70,
    energy: 30,
    genres: ["Pop", "Soul"],
    mood: "romantic",
  },
  {
    id: 607,
    title: "Your Song",
    artist: "Elton John",
    duration: "4:02",
    durationSeconds: 242,
    bpm: 80,
    energy: 35,
    genres: ["Pop", "Rock"],
    mood: "romantic",
  },
  {
    id: 608,
    title: "Unchained Melody",
    artist: "The Righteous Brothers",
    duration: "3:38",
    durationSeconds: 218,
    bpm: 60,
    energy: 40,
    genres: ["Pop", "Soul"],
    mood: "romantic",
  },
  {
    id: 609,
    title: "The Way You Look Tonight",
    artist: "Frank Sinatra",
    duration: "3:23",
    durationSeconds: 203,
    bpm: 120,
    energy: 35,
    genres: ["Jazz", "Vocal"],
    mood: "romantic",
  },
  {
    id: 610,
    title: "I Will Always Love You",
    artist: "Whitney Houston",
    duration: "4:31",
    durationSeconds: 271,
    bpm: 67,
    energy: 45,
    genres: ["Pop", "R&B"],
    mood: "romantic",
  },
  {
    id: 611,
    title: "My Heart Will Go On",
    artist: "Celine Dion",
    duration: "4:36",
    durationSeconds: 276,
    bpm: 50,
    energy: 40,
    genres: ["Pop", "Soundtrack"],
    mood: "romantic",
  },
  {
    id: 612,
    title: "Endless Love",
    artist: "Lionel Richie & Diana Ross",
    duration: "4:26",
    durationSeconds: 266,
    bpm: 65,
    energy: 35,
    genres: ["Pop", "R&B"],
    mood: "romantic",
  },
  {
    id: 613,
    title: "Just the Way You Are",
    artist: "Bruno Mars",
    duration: "3:40",
    durationSeconds: 220,
    bpm: 109,
    energy: 50,
    genres: ["Pop", "R&B"],
    mood: "romantic",
  },
  {
    id: 614,
    title: "Wonderful Tonight",
    artist: "Eric Clapton",
    duration: "3:42",
    durationSeconds: 222,
    bpm: 80,
    energy: 30,
    genres: ["Rock", "Blues"],
    mood: "romantic",
  },
  {
    id: 615,
    title: "Let's Stay Together",
    artist: "Al Green",
    duration: "3:18",
    durationSeconds: 198,
    bpm: 100,
    energy: 45,
    genres: ["Soul", "R&B"],
    mood: "romantic",
  },
  {
    id: 616,
    title: "Lovesong",
    artist: "The Cure",
    duration: "3:29",
    durationSeconds: 209,
    bpm: 134,
    energy: 50,
    genres: ["Rock", "Alternative"],
    mood: "romantic",
  },
  {
    id: 617,
    title: "God Only Knows",
    artist: "The Beach Boys",
    duration: "2:51",
    durationSeconds: 171,
    bpm: 117,
    energy: 40,
    genres: ["Pop", "Rock"],
    mood: "romantic",
  },
  {
    id: 618,
    title: "La Vie En Rose",
    artist: "Édith Piaf",
    duration: "3:11",
    durationSeconds: 191,
    bpm: 90,
    energy: 35,
    genres: ["French", "Chanson"],
    mood: "romantic",
  },
  {
    id: 619,
    title: "Something",
    artist: "The Beatles",
    duration: "3:03",
    durationSeconds: 183,
    bpm: 66,
    energy: 40,
    genres: ["Rock", "Pop"],
    mood: "romantic",
  },
  {
    id: 620,
    title: "Crazy Love",
    artist: "Van Morrison",
    duration: "2:40",
    durationSeconds: 160,
    bpm: 80,
    energy: 35,
    genres: ["Rock", "Folk"],
    mood: "romantic",
  },

  // Angry songs
  {
    id: 701,
    title: "Break Stuff",
    artist: "Limp Bizkit",
    duration: "2:46",
    durationSeconds: 166,
    bpm: 99,
    energy: 95,
    genres: ["Rock", "Metal"],
    mood: "angry",
  },
  {
    id: 702,
    title: "Bulls on Parade",
    artist: "Rage Against the Machine",
    duration: "3:51",
    durationSeconds: 231,
    bpm: 90,
    energy: 90,
    genres: ["Rock", "Metal"],
    mood: "angry",
  },
  {
    id: 703,
    title: "Killing in the Name",
    artist: "Rage Against the Machine",
    duration: "5:13",
    durationSeconds: 313,
    bpm: 93,
    energy: 95,
    genres: ["Rock", "Metal"],
    mood: "angry",
  },
  {
    id: 704,
    title: "Master of Puppets",
    artist: "Metallica",
    duration: "8:35",
    durationSeconds: 515,
    bpm: 220,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 705,
    title: "Chop Suey!",
    artist: "System of a Down",
    duration: "3:30",
    durationSeconds: 210,
    bpm: 127,
    energy: 85,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 706,
    title: "Du Hast",
    artist: "Rammstein",
    duration: "3:54",
    durationSeconds: 234,
    bpm: 125,
    energy: 90,
    genres: ["Metal", "Industrial"],
    mood: "angry",
  },
  {
    id: 707,
    title: "Sabotage",
    artist: "Beastie Boys",
    duration: "2:58",
    durationSeconds: 178,
    bpm: 146,
    energy: 90,
    genres: ["Hip Hop", "Rock"],
    mood: "angry",
  },
  {
    id: 708,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    duration: "5:01",
    durationSeconds: 301,
    bpm: 117,
    energy: 85,
    genres: ["Rock", "Grunge"],
    mood: "angry",
  },
  {
    id: 709,
    title: "Toxicity",
    artist: "System of a Down",
    duration: "3:39",
    durationSeconds: 219,
    bpm: 120,
    energy: 85,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 710,
    title: "One Step Closer",
    artist: "Linkin Park",
    duration: "2:37",
    durationSeconds: 157,
    bpm: 95,
    energy: 90,
    genres: ["Rock", "Nu Metal"],
    mood: "angry",
  },
  {
    id: 711,
    title: "Raining Blood",
    artist: "Slayer",
    duration: "4:17",
    durationSeconds: 257,
    bpm: 210,
    energy: 95,
    genres: ["Metal", "Thrash"],
    mood: "angry",
  },
  {
    id: 712,
    title: "Duality",
    artist: "Slipknot",
    duration: "4:12",
    durationSeconds: 252,
    bpm: 120,
    energy: 95,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 713,
    title: "Psychosocial",
    artist: "Slipknot",
    duration: "4:42",
    durationSeconds: 282,
    bpm: 140,
    energy: 95,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 714,
    title: "Walk",
    artist: "Pantera",
    duration: "5:15",
    durationSeconds: 315,
    bpm: 90,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 715,
    title: "Down with the Sickness",
    artist: "Disturbed",
    duration: "4:38",
    durationSeconds: 278,
    bpm: 90,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 716,
    title: "Bodies",
    artist: "Drowning Pool",
    duration: "3:22",
    durationSeconds: 202,
    bpm: 104,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 717,
    title: "Bleed It Out",
    artist: "Linkin Park",
    duration: "2:44",
    durationSeconds: 164,
    bpm: 140,
    energy: 85,
    genres: ["Rock", "Alternative"],
    mood: "angry",
  },
  {
    id: 718,
    title: "B.Y.O.B.",
    artist: "System of a Down",
    duration: "4:15",
    durationSeconds: 255,
    bpm: 170,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 719,
    title: "Fuel",
    artist: "Metallica",
    duration: "4:29",
    durationSeconds: 269,
    bpm: 120,
    energy: 90,
    genres: ["Metal", "Rock"],
    mood: "angry",
  },
  {
    id: 720,
    title: "Last Resort",
    artist: "Papa Roach",
    duration: "3:20",
    durationSeconds: 200,
    bpm: 91,
    energy: 85,
    genres: ["Rock", "Nu Metal"],
    mood: "angry",
  },

  // Sleepy songs
  {
    id: 801,
    title: "Weightless",
    artist: "Marconi Union",
    duration: "8:09",
    durationSeconds: 489,
    bpm: 60,
    energy: 15,
    genres: ["Ambient", "Electronic"],
    mood: "sleepy",
  },
  {
    id: 802,
    title: "Claire de Lune",
    artist: "Claude Debussy",
    duration: "5:01",
    durationSeconds: 301,
    bpm: 70,
    energy: 20,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 803,
    title: "Sleepwalk",
    artist: "Santo & Johnny",
    duration: "2:24",
    durationSeconds: 144,
    bpm: 75,
    energy: 25,
    genres: ["Instrumental", "Rock"],
    mood: "sleepy",
  },
  {
    id: 804,
    title: "Moonlight Sonata",
    artist: "Ludwig van Beethoven",
    duration: "5:22",
    durationSeconds: 322,
    bpm: 60,
    energy: 20,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 805,
    title: "Comptine d'un autre été",
    artist: "Yann Tiersen",
    duration: "2:21",
    durationSeconds: 141,
    bpm: 80,
    energy: 25,
    genres: ["Soundtrack", "Piano"],
    mood: "sleepy",
  },
  {
    id: 806,
    title: "Sleep",
    artist: "Eric Whitacre",
    duration: "8:05",
    durationSeconds: 485,
    bpm: 60,
    energy: 15,
    genres: ["Classical", "Choral"],
    mood: "sleepy",
  },
  {
    id: 807,
    title: "Gymnopédie No.1",
    artist: "Erik Satie",
    duration: "3:05",
    durationSeconds: 185,
    bpm: 60,
    energy: 20,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 808,
    title: "Prelude in E-Minor",
    artist: "Frédéric Chopin",
    duration: "4:25",
    durationSeconds: 265,
    bpm: 65,
    energy: 25,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 809,
    title: "Lotus Flower",
    artist: "Radiohead",
    duration: "5:01",
    durationSeconds: 301,
    bpm: 115,
    energy: 40,
    genres: ["Alternative", "Electronic"],
    mood: "sleepy",
  },
  {
    id: 810,
    title: "Holocene",
    artist: "Bon Iver",
    duration: "5:36",
    durationSeconds: 336,
    bpm: 73,
    energy: 35,
    genres: ["Indie", "Folk"],
    mood: "sleepy",
  },
  {
    id: 811,
    title: "Bloom",
    artist: "The Paper Kites",
    duration: "3:28",
    durationSeconds: 208,
    bpm: 80,
    energy: 30,
    genres: ["Indie", "Folk"],
    mood: "sleepy",
  },
  {
    id: 812,
    title: "Albatross",
    artist: "Fleetwood Mac",
    duration: "3:10",
    durationSeconds: 190,
    bpm: 65,
    energy: 25,
    genres: ["Rock", "Instrumental"],
    mood: "sleepy",
  },
  {
    id: 813,
    title: "Avril 14th",
    artist: "Aphex Twin",
    duration: "2:05",
    durationSeconds: 125,
    bpm: 84,
    energy: 30,
    genres: ["Electronic", "Ambient"],
    mood: "sleepy",
  },
  {
    id: 814,
    title: "Treefingers",
    artist: "Radiohead",
    duration: "3:42",
    durationSeconds: 222,
    bpm: 60,
    energy: 20,
    genres: ["Electronic", "Ambient"],
    mood: "sleepy",
  },
  {
    id: 815,
    title: "Rêverie",
    artist: "Claude Debussy",
    duration: "4:39",
    durationSeconds: 279,
    bpm: 70,
    energy: 25,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 816,
    title: "Nocturne Op. 9 No. 2",
    artist: "Frédéric Chopin",
    duration: "4:33",
    durationSeconds: 273,
    bpm: 65,
    energy: 30,
    genres: ["Classical", "Piano"],
    mood: "sleepy",
  },
  {
    id: 817,
    title: "Watermark",
    artist: "Enya",
    duration: "2:26",
    durationSeconds: 146,
    bpm: 80,
    energy: 30,
    genres: ["New Age", "Celtic"],
    mood: "sleepy",
  },
  {
    id: 818,
    title: "Adagio for Strings",
    artist: "Samuel Barber",
    duration: "7:25",
    durationSeconds: 445,
    bpm: 55,
    energy: 35,
    genres: ["Classical", "Orchestral"],
    mood: "sleepy",
  },
  {
    id: 819,
    title: "Teardrop",
    artist: "Massive Attack",
    duration: "5:30",
    durationSeconds: 330,
    bpm: 79,
    energy: 45,
    genres: ["Trip Hop", "Electronic"],
    mood: "sleepy",
  },
  {
    id: 820,
    title: "Svefn-g-englar",
    artist: "Sigur Rós",
    duration: "10:04",
    durationSeconds: 604,
    bpm: 60,
    energy: 40,
    genres: ["Post-Rock", "Ambient"],
    mood: "sleepy",
  },
]

// Cover images for different moods
const moodCovers = {
  happy: "/mood-covers/happy-cover.png",
  chill: "/mood-covers/chill-cover.png",
  energetic: "/mood-covers/energetic-cover.png",
  melancholic: "/mood-covers/melancholic-cover.jpg",
  focus: "/mood-covers/focus-cover.png",
  romantic: "/mood-covers/romantic-cover.png",
  angry: "/mood-covers/angry-cover.png",
  sleepy: "/mood-covers/sleepy-cover.png",
}

// Playlist title templates for different moods
const playlistTitles = {
  happy: ["Happy Vibes", "Sunshine Beats", "Joyful Tunes", "Uplifting Melodies"],
  chill: ["Chill Zone", "Relaxed Rhythms", "Laid Back", "Easy Listening"],
  energetic: ["Energy Boost", "Power Beats", "High Voltage", "Adrenaline Rush"],
  melancholic: ["Melancholy Moments", "Rainy Day", "Reflective Mood", "Soulful Echoes"],
  focus: ["Deep Focus", "Concentration", "Study Session", "Mind Flow"],
  romantic: ["Love Notes", "Romantic Evening", "Heart Beats", "Soulful Connection"],
  angry: ["Rage Release", "Fury Beats", "Anger Management", "Intense Energy"],
  sleepy: ["Dreamy Night", "Sleep Sounds", "Bedtime Playlist", "Gentle Lullabies"],
}

// Helper function to format total duration
function formatTotalDuration(seconds: number) {
  const hours = Math.floor(seconds / 3600)
  const minutes = Math.floor((seconds % 3600) / 60)
  const secs = seconds % 60

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`
  } else {
    return `${minutes}:${secs.toString().padStart(2, "0")}`
  }
}

// Helper function to get a random subset of songs
function getRandomSubset(array: any[], size: number) {
  const shuffled = [...array].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, size)
}

// Helper function to repeat songs to fill duration
function repeatSongsToFillDuration(songs: any[], targetDurationSeconds: number) {
  const result = [...songs]
  let totalDuration = songs.reduce((sum, song) => sum + song.durationSeconds, 0)

  // If we already have enough duration, return the original songs
  if (totalDuration >= targetDurationSeconds) {
    return result
  }

  // Otherwise, keep adding songs until we reach the target duration
  const originalSongs = [...songs]
  while (totalDuration < targetDurationSeconds) {
    // Get a random song from the original set
    const randomSong = originalSongs[Math.floor(Math.random() * originalSongs.length)]
    result.push(randomSong)
    totalDuration += randomSong.durationSeconds
  }

  return result
}

export async function POST(request: Request) {
  try {
    const { mood, duration, bpmRange, energyLevel, genres } = await request.json()

    // Calculate target duration in seconds
    const targetDurationSeconds = duration * 60

    console.log(
      `Generating playlist for mood: ${mood}, duration: ${duration} minutes (${targetDurationSeconds} seconds)`,
    )

    // Filter songs by mood
    let filteredSongs = songDatabase.filter((song) => song.mood === mood)
    console.log(`Found ${filteredSongs.length} songs for mood: ${mood}`)

    // Apply BPM filter if specified
    if (bpmRange && bpmRange.length === 2) {
      const originalCount = filteredSongs.length
      filteredSongs = filteredSongs.filter((song) => song.bpm >= bpmRange[0] && song.bpm <= bpmRange[1])
      console.log(`BPM filter (${bpmRange[0]}-${bpmRange[1]}): ${originalCount} -> ${filteredSongs.length} songs`)

      // If too restrictive, relax the filter
      if (filteredSongs.length < 5) {
        console.log("BPM filter too restrictive, relaxing...")
        const relaxedMinBpm = Math.max(60, bpmRange[0] - 20)
        const relaxedMaxBpm = Math.min(200, bpmRange[1] + 20)
        filteredSongs = songDatabase.filter(
          (song) => song.mood === mood && song.bpm >= relaxedMinBpm && song.bpm <= relaxedMaxBpm,
        )
        console.log(`Relaxed BPM filter (${relaxedMinBpm}-${relaxedMaxBpm}): ${filteredSongs.length} songs`)
      }
    }

    // Apply energy level filter if specified
    if (energyLevel !== undefined) {
      const originalCount = filteredSongs.length
      // Allow some flexibility (±20%)
      const minEnergy = Math.max(0, energyLevel - 20)
      const maxEnergy = Math.min(100, energyLevel + 20)
      filteredSongs = filteredSongs.filter((song) => song.energy >= minEnergy && song.energy <= maxEnergy)
      console.log(`Energy filter (${minEnergy}-${maxEnergy}): ${originalCount} -> ${filteredSongs.length} songs`)

      // If too restrictive, relax the filter
      if (filteredSongs.length < 5) {
        console.log("Energy filter too restrictive, relaxing...")
        const relaxedMinEnergy = Math.max(0, energyLevel - 40)
        const relaxedMaxEnergy = Math.min(100, energyLevel + 40)
        filteredSongs = songDatabase.filter(
          (song) => song.mood === mood && song.energy >= relaxedMinEnergy && song.energy <= relaxedMaxEnergy,
        )
        console.log(`Relaxed energy filter (${relaxedMinEnergy}-${relaxedMaxEnergy}): ${filteredSongs.length} songs`)
      }
    }

    // Apply genre filter if specified
    if (genres && genres.length > 0) {
      const originalCount = filteredSongs.length
      filteredSongs = filteredSongs.filter((song) => genres.some((genre: string) => song.genres.includes(genre)))
      console.log(`Genre filter (${genres.join(", ")}): ${originalCount} -> ${filteredSongs.length} songs`)

      // If too restrictive, relax the filter
      if (filteredSongs.length < 5) {
        console.log("Genre filter too restrictive, falling back to mood-only filter")
        filteredSongs = songDatabase.filter((song) => song.mood === mood)
      }
    }

    // If no songs match the filters, fall back to mood-only filter
    if (filteredSongs.length === 0) {
      console.log("No songs match all filters, falling back to mood-only filter")
      filteredSongs = songDatabase.filter((song) => song.mood === mood)
    }

    // Shuffle the filtered songs
    filteredSongs = [...filteredSongs].sort(() => Math.random() - 0.5)

    // Calculate how many songs we need to fill the duration
    // For longer durations, we need to handle the case where we might not have enough songs
    let totalDurationSeconds = 0
    let selectedSongs: typeof filteredSongs = []

    // First pass: try to fill as much as possible with unique songs
    for (const song of filteredSongs) {
      if (totalDurationSeconds + song.durationSeconds <= targetDurationSeconds) {
        selectedSongs.push(song)
        totalDurationSeconds += song.durationSeconds
      }
    }

    console.log(
      `First pass: Selected ${selectedSongs.length} songs, total duration: ${formatTotalDuration(totalDurationSeconds)} (target: ${formatTotalDuration(targetDurationSeconds)})`,
    )

    // If we don't have enough songs to fill the duration, we need to repeat some songs
    if (totalDurationSeconds < targetDurationSeconds * 0.9 && selectedSongs.length > 0) {
      console.log("Not enough songs to fill duration, repeating songs...")

      // For very long durations, we might need to repeat songs multiple times
      // We'll keep adding songs until we reach at least 90% of the target duration
      while (totalDurationSeconds < targetDurationSeconds * 0.9) {
        // Get a random song from our filtered set
        const randomSong = filteredSongs[Math.floor(Math.random() * filteredSongs.length)]

        // Add it to our selection
        selectedSongs.push(randomSong)
        totalDurationSeconds += randomSong.durationSeconds
      }

      console.log(
        `After repeating: ${selectedSongs.length} songs, total duration: ${formatTotalDuration(totalDurationSeconds)}`,
      )
    }

    // If we still don't have enough songs (very unlikely), we'll just use what we have
    if (selectedSongs.length === 0) {
      console.log("No songs selected, using all filtered songs")
      selectedSongs = filteredSongs
      totalDurationSeconds = selectedSongs.reduce((sum, song) => sum + song.durationSeconds, 0)
    }

    // Generate a random title for the playlist based on mood
    const moodTitles = playlistTitles[mood as keyof typeof playlistTitles] || playlistTitles.happy
    const playlistTitle = moodTitles[Math.floor(Math.random() * moodTitles.length)]

    // Get cover image for the mood
    const coverImage = moodCovers[mood as keyof typeof moodCovers] || "/colorful-abstract-music-album-cover.png"

    // Create the playlist object
    const playlist = {
      title: playlistTitle,
      coverImage,
      songs: selectedSongs,
      totalDuration: formatTotalDuration(totalDurationSeconds),
      totalDurationSeconds,
      mood: mood.charAt(0).toUpperCase() + mood.slice(1), // Capitalize first letter
    }

    console.log(`Generated playlist: ${playlist.title}, ${playlist.songs.length} songs, ${playlist.totalDuration}`)

    return NextResponse.json({ playlist })
  } catch (error) {
    console.error("Error generating playlist:", error)
    return NextResponse.json({ error: "Failed to generate playlist" }, { status: 500 })
  }
}
